/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

drop schema if exists "proc" cascade;

CREATE SCHEMA "proc";{{ template "user_setcountry.sql".}} 
{{ template "user_clearcountry.sql".}} 
{{ template "user_create_proc.sql".}} 
{{ template "user_update_proc.sql".}} 
{{ template "user_delete_proc.sql".}} 
{{ template "user_undo_delete_proc.sql".}} 
{{ template "country_create_proc.sql".}} 
{{ template "country_update_proc.sql".}} 
{{ template "country_delete_proc.sql".}} 
{{ template "country_undo_delete_proc.sql".}} 
{{ template "site_create_proc.sql".}} 
{{ template "site_update_proc.sql".}} 
{{ template "site_delete_proc.sql".}} 
{{ template "site_undo_delete_proc.sql".}} 
{{ template "building_create_proc.sql".}} 
{{ template "building_update_proc.sql".}} 
{{ template "building_delete_proc.sql".}} 
{{ template "building_undo_delete_proc.sql".}} 
{{ template "floor_create_proc.sql".}} 
{{ template "floor_update_proc.sql".}} 
{{ template "floor_delete_proc.sql".}} 
{{ template "floor_undo_delete_proc.sql".}} 
{{ template "desk_create_proc.sql".}} 
{{ template "desk_update_proc.sql".}} 
{{ template "desk_delete_proc.sql".}} 
{{ template "desk_undo_delete_proc.sql".}} 
{{ template "restrictiongroup_adddesk.sql".}} 
{{ template "restrictiongroup_removedesk.sql".}} 
{{ template "restrictiongroup_adduser.sql".}} 
{{ template "restrictiongroup_removeuser.sql".}} 
{{ template "restrictiongroup_create_proc.sql".}} 
{{ template "restrictiongroup_update_proc.sql".}} 
{{ template "restrictiongroup_delete_proc.sql".}} 
{{ template "restrictiongroup_undo_delete_proc.sql".}} 
{{ template "booking_createbooking.sql".}} 
{{ template "booking_deletebooking.sql".}} 
{{ template "booking_movebooking.sql".}} 
{{ template "booking_changebooking.sql".}} 
{{ template "booking_create_proc.sql".}} 
{{ template "booking_update_proc.sql".}} 
{{ template "booking_delete_proc.sql".}} 
{{ template "booking_undo_delete_proc.sql".}} 

