// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Web deploy to Test
---
*/
package cmds

import (
	"context"

	"github.com/nexi-intra/nexi-booking/execution"
	"github.com/nexi-intra/nexi-booking/utils"
)

func ProvisionWebdeploytestPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magic-people", "60-provision", "11-web-test.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
