/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UXfgzdQfwdx
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { ResponsiveBar } from "@nivo/bar";
import { ResponsiveLine } from "@nivo/line";

export function Dashboard() {
  return (
    <div className="flex h-screen">
      <aside className="w-64 bg-[#f5f5ff] p-4">
        <div className="flex items-center justify-center mb-8">
          <img src="/placeholder.svg" alt="Logo" className="h-10 w-10" />
        </div>
        <nav className="space-y-4">
          <a href="#" className="flex items-center space-x-2 text-gray-700">
            <LayoutDashboardIcon className="h-5 w-5" />
            <span>Dashboard</span>
          </a>
          <a href="#" className="flex items-center space-x-2 text-gray-700">
            <StoreIcon className="h-5 w-5" />
            <span>Customer</span>
          </a>
          <a href="#" className="flex items-center space-x-2 text-gray-700">
            <CurrencyIcon className="h-5 w-5" />
            <span>Earnings</span>
          </a>
          <a href="#" className="flex items-center space-x-2 text-gray-700">
            <ShoppingCartIcon className="h-5 w-5" />
            <span>Product Sales</span>
          </a>
          <a href="#" className="flex items-center space-x-2 text-gray-700">
            <StoreIcon className="h-5 w-5" />
            <span>Store Management</span>
          </a>
          <a href="#" className="flex items-center space-x-2 text-gray-700">
            <SettingsIcon className="h-5 w-5" />
            <span>Settings</span>
          </a>
        </nav>
        <div className="mt-auto">
          <div className="flex items-center justify-center mb-4">
            <img src="/placeholder.svg" alt="Upgrade" className="h-24 w-24" />
          </div>
          <Button className="w-full">Upgrade Now</Button>
        </div>
      </aside>
      <main className="flex-1 p-6 bg-[#f5f5ff]">
        <header className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold">Dashboard</h1>
          <div className="flex items-center space-x-4">
            <Input type="search" placeholder="Search..." className="w-64" />
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>KW</AvatarFallback>
            </Avatar>
          </div>
        </header>
        <section className="grid grid-cols-3 gap-6 mb-6">
          <Card className="p-4">
            <CardHeader>
              <CardTitle>Store Status</CardTitle>
            </CardHeader>
            <CardContent>
              <BarChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
          <Card className="p-4">
            <CardHeader>
              <CardTitle>Total Sales</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
          <Card className="p-4">
            <CardHeader>
              <CardTitle>Total Profit</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
        </section>
        <section className="grid grid-cols-3 gap-6 mb-6">
          <Card className="col-span-2 p-4">
            <CardHeader>
              <CardTitle>Earnings</CardTitle>
              <CardDescription>$20,885</CardDescription>
            </CardHeader>
            <CardContent>
              <LineChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
          <div className="space-y-6">
            <Card className="p-4">
              <CardHeader>
                <CardTitle>Total Sales by Unit</CardTitle>
                <CardDescription>$473.58</CardDescription>
              </CardHeader>
              <CardContent>
                <BarChart className="w-full aspect-[4/3]" />
              </CardContent>
            </Card>
            <Card className="p-4">
              <CardHeader>
                <CardTitle>Members Online</CardTitle>
                <CardDescription>920</CardDescription>
              </CardHeader>
            </Card>
            <Card className="p-4">
              <CardHeader>
                <CardTitle>Server Load</CardTitle>
                <CardDescription>920</CardDescription>
              </CardHeader>
            </Card>
            <Card className="p-4">
              <CardHeader>
                <CardTitle>Today&apos;s Revenue</CardTitle>
                <CardDescription>$854</CardDescription>
              </CardHeader>
            </Card>
          </div>
        </section>
        <section className="grid grid-cols-2 gap-6">
          <Card className="p-4">
            <CardHeader>
              <CardTitle>Products List</CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Products Name</TableHead>
                    <TableHead>Sale</TableHead>
                    <TableHead>Pricing</TableHead>
                    <TableHead>Stock Status</TableHead>
                    <TableHead>Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell className="flex items-center space-x-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>GZ</AvatarFallback>
                      </Avatar>
                      <div>
                        <div>Galaxy Z Fold3 5G</div>
                        <div className="text-sm text-muted-foreground">
                          #5486726054
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>50</TableCell>
                    <TableCell>$1200.66</TableCell>
                    <TableCell className="text-green-500">Available</TableCell>
                    <TableCell>
                      <OptionIcon className="h-5 w-5" />
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="flex items-center space-x-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>GZ</AvatarFallback>
                      </Avatar>
                      <div>
                        <div>Galaxy Z Fold3 5G</div>
                        <div className="text-sm text-muted-foreground">
                          #5486726054
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>80</TableCell>
                    <TableCell>$200.00</TableCell>
                    <TableCell className="text-red-500">Unavailable</TableCell>
                    <TableCell>
                      <OptionIcon className="h-5 w-5" />
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="flex items-center space-x-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>GZ</AvatarFallback>
                      </Avatar>
                      <div>
                        <div>Galaxy Z Fold3 5G</div>
                        <div className="text-sm text-muted-foreground">
                          #5486726054
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>40</TableCell>
                    <TableCell>$600.70</TableCell>
                    <TableCell className="text-green-500">Available</TableCell>
                    <TableCell>
                      <OptionIcon className="h-5 w-5" />
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card className="p-4">
            <CardHeader>
              <CardTitle>User Activity</CardTitle>
            </CardHeader>
            <CardContent>
              <BarChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
        </section>
      </main>
    </div>
  );
}

function BarChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  );
}

function CurrencyIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="8" />
      <line x1="3" x2="6" y1="3" y2="6" />
      <line x1="21" x2="18" y1="3" y2="6" />
      <line x1="3" x2="6" y1="21" y2="18" />
      <line x1="21" x2="18" y1="21" y2="18" />
    </svg>
  );
}

function LayoutDashboardIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="9" x="3" y="3" rx="1" />
      <rect width="7" height="5" x="14" y="3" rx="1" />
      <rect width="7" height="9" x="14" y="12" rx="1" />
      <rect width="7" height="5" x="3" y="16" rx="1" />
    </svg>
  );
}

function LineChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  );
}

function OptionIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 3h6l6 18h6" />
      <path d="M14 3h7" />
    </svg>
  );
}

function SettingsIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}

function ShoppingCartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  );
}

function StoreIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7" />
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <path d="M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4" />
      <path d="M2 7h20" />
      <path d="M22 7v3a2 2 0 0 1-2 2v0a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12v0a2 2 0 0 1-2-2V7" />
    </svg>
  );
}
